name: Publish npm package

on:
  push:
    branches:
      - main  # Asegúrate de usar el nombre correcto de tu rama principal

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'  # Puedes especificar la versión de Node.js que necesites
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION }}